<?php

add_ux_builder_shortcode( 'title', array(
	'name'      => __( 'Title', 'ux-builder' ),
	'category'  => __( 'Content' ),
	'template'  => flatsome_uxf_builder_template( 'title.html' ),
    'thumbnail' => get_template_directory_uri() . '/inc/builder/shortcodes/thumbnails/title.svg',
	'info'      => '{{ text }}',
	'wrap'      => false,
    'styles' => array(
      'uxf-animate' => UXF_URL . 'assets/css/animate.min.css',
      'uxf-hover' => UXF_URL . 'assets/css/hover.min.css'
    ),
    'scripts' => array(
      'uxf-anidynamic' => UXF_URL . 'assets/js/animate.min.js',
    ),

	'options' => array(
		'style' => array(
			'type'    => 'select',
			'heading' => 'Style',
			'default' => 'normal',
			'options' => array(
				'normal'      => 'Normal',
				'center'      => 'Center',
				'bold'        => 'Left Bold',
				'bold-center' => 'Center Bold',
			),
		),
		'text' => array(
			'type'       => 'textfield',
			'heading'    => 'Title',
			'default'    => 'Lorem ipsum dolor sit amet...',
			'auto_focus' => true,
		),
		'sub_text' => array(
			'type'       => 'textfield',
			'heading'    => 'Sub Title',
			'default'    => '',
		),
		'text_options'     => array(
			'type'    => 'group',
			'heading' => 'Text Options',
			'options' => array(
				'tag_name' => array(
					'type'    => 'select',
					'heading' => 'Tag',
					'default' => 'h3',
					'options' => array(
						'h2' => 'H2',
						'h3' => 'H3',
						'h4' => 'H4',
						'h5' => 'H5',
						'h6' => 'H6',
						'p' => 'P',
						'div' => 'DIV',
					),
				),
				'icon' => array(
					'type'    => 'select',
					'heading' => 'Icon',
					'options' => require( get_template_directory() . '/inc/builder/shortcodes/values/icons.php' ),
				),
				'size' => array(
					'type'    => 'slider',
					'heading' => __( 'Size' ),
					'default' => 100,
					'unit'    => '%',
					'min'     => 20,
					'max'     => 300,
					'step'    => 1,
				),
				'link' => array(
					'type'    => 'textfield',
					'heading' => 'Link',
					'default' => '',
				),
                'link_text' => array(
                    'type'    => 'textfield',
                    'heading' => 'Link Text',
                    'default' => '',
                ),
				'target' => array(
					'type' => 'select',
					'heading' => __( 'Target' ),
					'default' => '',
					'options' => array(
						'' => 'Same window',
						'_blank' => 'New window',
					)
				  ),
				'color' => array(
					'type'     => 'colorpicker',
					'heading'  => __( 'Text Color' ),
					'format'   => 'rgb',
					'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
				),
				'box_color' => array(
					'type'     => 'colorpicker',
					'heading'  => __( 'Box Color' ),
					'format'   => 'rgb',
					'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
				),
				'box_padding' => array(
					'type' => 'margins',
					'heading' => 'Box Padding',
					'full_width' => true,
					'min' => 0,
					'max' => 100,
					'step' => 1,
				),
				'box_margin' => array(
					'type' => 'margins',
					'heading' => 'Box Margin',
					'full_width' => true,
					'min' => -100,
					'max' => 100,
					'step' => 1,
				),
                'box_radius' => array(
                    'type' => 'slider',
                    'heading' => 'Box Radius',
                    'conditions' => 'box_color',
                    'unit' => 'px',
                    'min' => 0,
                    'max' => 100,
                    'step' => 1,
                ),
			),
		),
		'container_options'     => array(
				'type'    => 'group',
				'heading' => 'Container Options',
				'options' => array(
					'bg_color' => array(
						'type'     => 'colorpicker',
						'heading'  => __( 'Background Color' ),
						'alpha'    => true,
						'format'   => 'rgb',
						'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
					),
					'bg_transform' => array(
						'conditions' => 'bg_color',
						'type'        => 'slider',
						'heading'     => __( 'Bg Transform' ),
						'default'	  => '',
						'min'         => 0,
						'max'         => 360,
						'step'        => 5,
					),
					'text_transform'      => array(
						'conditions' => 'bg_color',
						'type'    => 'checkbox',
						'heading'     => __( 'Text Transform' ),
					),
					'width' => array(
						'type'    => 'scrubfield',
						'heading' => __( 'Width' ),
						'min'     => 0,
						'max'     => 1200,
						'step'    => 5,
					),
					'padding' => array(
						'type' => 'margins',
						'heading' => 'Padding',
						'full_width' => true,
						'min' => 0,
						'max' => 100,
						'step' => 1,
					),
                    'margin_top' => array(
                        'type'        => 'scrubfield',
                        'heading'     => __( 'Margin Top' ),
                        'default'     => '',
                        'placeholder' => __( '0px' ),
                        'min'         => - 100,
                        'max'         => 300,
                        'step'        => 1,
                    ),
                    'margin_bottom' => array(
                        'type'        => 'scrubfield',
                        'heading'     => __( 'Margin Bottom' ),
                        'default'     => '',
                        'placeholder' => __( '0px' ),
                        'min'         => - 100,
                        'max'         => 300,
                        'step'        => 1,
                    ),
				),
			),
		'border_options'     => array(
			'type'    => 'group',
			'heading' => 'Border Options',
			'options' => array(
				'm_border_color' => array(
					'type'     => 'colorpicker',
					'heading'  => __( 'Main Border Color' ),
					'format'   => 'rgb',
					'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
				),
				'm_border_width' => array(
					'type'    => 'scrubfield',
					'heading' => __( 'Main Border Width' ),
					'default' => '',
					'min'     => 0,
					'max'     => 100,
					'step'    => 1,
				),
				'b_border_color' => array(
                    'type' => 'colorpicker',
                    'heading' => __('Border Color'),
                    'format' => 'rgb',
                    'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
				),
				'b_border_width' => array(
					'type'    => 'scrubfield',
					'heading' => __( 'Border Width' ),
					'default' => '',
					'min'     => 0,
					'max'     => 100,
					'step'    => 1,
				),
				'b_height' => array(
					'conditions' => 'style !== "normal"',
					'type'    => 'scrubfield',
					'heading' => __( 'Divider Height' ),
					'default' => '',
					'min'     => 0,
					'max'     => 200,
					'step'    => 1,
				),
				'b_bg_color' => array(
					'conditions' => 'b_height',
					'type'     => 'colorpicker',
					'heading'  => __( 'Divider Color' ),
					'format'   => 'rgb',
					'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
				),
				'b_transform' => array(
					'conditions' => 'b_height',
					'type'        => 'slider',
					'heading'     => __( 'Divider Transform' ),
					'min'         => 0,
					'max'         => 360,
					'step'        => 5,
				),
				'b_opacity' => array(
					'conditions' => 'b_height',
					'type'    => 'slider',
					'heading' => __( 'Divider Opacity' ),
					'default' => '',
					'min'     => 0.1,
					'max'     => 1,
					'step'    => 0.1,
				),
			),
		),
		'advanced_options' => require( get_template_directory() . '/inc/builder/shortcodes/commons/advanced.php'),
	),
) );
