<?php

return array(
      'type' => 'group',
      'heading' => __( 'Background' ),
      'options' => array(
        'bg' => array(
          'type' => 'image',
          'heading' => __( 'Image' ),
          'thumb_size' => 'bg_size',
          'bg_position' => 'bg_pos',
        ),
        'bg_size'=> array(
          'type' => 'select',
          'heading' => 'Size',
          'default' => 'large',
          'conditions' => 'bg',
          'options' => flatsome_uxf_builder_image_sizes(),
        ),
        'bg_color' => array(
          'type' => 'colorpicker',
          'heading' => __('Color'),
          'format' => 'rgb',
          'position' => 'bottom right',
          'helpers' => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
        ),
        'bg_overlay' => array(
          'type' => 'colorpicker',
          'heading' => __('Overlay'),
          'responsive' => true,
          'alpha' => true,
          'format' => 'rgb',
          'position' => 'bottom right',
          'helpers' => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors-overlay.php' ),
        ),
        'bg_gradient' => array(
          'type'     => 'colorpicker',
          'heading'  => __( 'BG Gradient', 'flatsome' ),
          'default' => '',
          'format'   => 'rgb',
          'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
          'conditions' => 'bg_color',
        ),
        'bg_gradient_to' => array(
          'conditions' => 'bg_gradient',
          'type' => 'radio-buttons',
          'heading' => 'Gradient To',
          'full_width' => true,
          'default' => 'left',
          'options' => array(
            'top'   => array( 'title' => 'Top'),
            'left'   => array( 'title' => 'Left'),
            'right'   => array( 'title' => 'Right'),
            'bottom'   => array( 'title' => 'Bottom'),
            ),
          ),
        'bg_pos' => array(
          'conditions' => 'bg',
          'type' => 'textfield',
          'heading' => __('Position'),
        ),
        'bg_cover' => array(
          'conditions' => 'bg',
          'type' => 'radio-buttons',
          'heading' => __('Bg Cover'),
          'default' => '',
          'options' => array(
            ''   => array( 'title' => 'Cover'),
            'contain'   => array( 'title' => 'Contain'),
            'none'   => array( 'title' => 'None'),
            ),
        ),
        'bg_repeat' => array(
          'conditions' => 'bg',
          'type' => 'radio-buttons',
          'heading' => __('Bg Repeat'),
          'default' => '',
          'options' => array(
            ''   => array( 'title' => 'No Repeat'),
            'repeat'   => array( 'title' => 'Repeat'),
            'repeat-x'   => array( 'title' => 'Repeat X'),
            'repeat-y'   => array( 'title' => 'Repeat Y'),
            ),
        ),
        'bg_radius' => array(
            'type' => 'slider',
            'heading' => 'Radius',
            'unit' => 'px',
            'min' => 0,
            'max' => 100,
            'step' => 1,
        ),
        'bg_overflow' => array(
            'type' => 'radio-buttons',
            'heading' => 'Bg Overflow',
            'default' => '',
            'options' => array(
                ''  => array( 'title' => 'Visible'),
                'hidden'  => array( 'title' => 'Hidden'),
            ),
            'conditions' => 'bg_radius',
        ),
        'hover' => array(
          'type' => 'select',
          'heading' => 'Hover',
          'options' => require( get_template_directory() . '/inc/builder/shortcodes/values/image-hover.php' ),
        ),
        'hover_alt' => array(
          'type' => 'select',
          'heading' => 'Hover Alt',
          'options' => require( get_template_directory() . '/inc/builder/shortcodes/values/image-hover.php' ),
        ),
        'bg_hover' => array(
          'conditions' => 'bg',
          'type' => 'select',
          'heading' => 'Bg Hover',
          'default' => '',
          'options' => array(
              '' => 'Off',
              'fade' => 'Fade',
              'rotatey' => 'Rotate Y',
              'scalein' => 'Scale In',
              'scaleout' => 'Scale Out',
              'translatex' => 'Translate X',
              'circle' => 'Circle',
            ),
          ),
        'parallax' => array(
            'conditions' => 'bg',
            'type' => 'slider',
            'heading' => 'Parallax',
            'unit' => '+',
            'default' => 0,
            'max' => 10,
            'min' => 0,
        ),
       'effect' => array(
            'type' => 'select',
            'heading' => 'Effects',
            'options' => array(
              '' => 'No effect',
              'snow' => 'Snow',
              'confetti' => 'Confetti',
              'sliding-glass' => 'Sliding Glass',
              'sparkle' => 'Sparkle',
              'rain' => 'Rain',
              'bubbles bubbles-circle' => 'Bubbles Circle',
              'bubbles bubbles-round' => 'Bubbles Round',
              'bubbles bubbles-square' => 'Bubbles Square',
              'cube cube-circle' => 'Cube Circle',
              'cube cube-square' => 'Cube Square',
              'random' => 'Random',
              'waves waves-one' => 'One Waves',
              'waves waves-two' => 'Two Waves',
              'waves waves-three' => 'Three Waves',
              'sliding' => 'Sliding',
            ),
        ),
    ),
);