<?php
// AnimateCSS Control
return array(
      'type' => 'group',
      'heading' => __( 'UXF Style' ),
      'options' => array(
        'icon_dot'      => array(
            'type'    => 'checkbox',
            'heading' => 'Icon Dot',
        ),
        'icon'        => array(
            'conditions' => 'icon_dot == ""',
            'type'    => 'select',
            'heading' => 'Icon',
            'options' => require( UXF_PATH . '/inc/builder/shortcodes/values/icons.php' ),
        ),
        'icon_custom' => array(
            'conditions' => 'icon == "custom"',
            'type'       => 'textfield',
            'heading'    => 'Icon Class',
            'default'    => '',
        ),
        'icon_size' => array(
            'conditions' => 'icon && icon_dot == ""',
            'type' => 'scrubfield',
            'heading' => __( 'Icon Size' ),
            'default' => '16px',
            'min' => 0,
        ),
        'icon_color' => array(
            'type'     => 'colorpicker',
            'heading'  => __( 'Icon Color' ),
            'default' => '',
            'format'   => 'hex',
            'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
        ),
        'icon_border' => array(
            'type'     => 'colorpicker',
            'heading'  => __( 'Icon Border' ),
            'default' => '',
            'format'   => 'hex',
            'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
        ),
        'icon_border_width' => array(
          'type'    => 'slider',
          'heading' => __( 'Icon Border Width' ),
          'unit' => 'px',
          'max'        => 100,
          'min'        => 0,
          'step'       => 1,
        ),
        'icon_margin' => array(
          'type'    => 'slider',
          'heading' => __( 'Icon Margin Top' ),
          'default'    => '-10',
          'unit' => '+',
          'max'        => 50,
          'min'        => -50,
          'step'       => 1,
        ),
        'icon_padding' => array(
          'type'    => 'slider',
          'heading' => __( 'Icon Padding' ),
          'unit' => 'px',
          'max'        => 100,
          'min'        => 0,
          'step'       => 1,
        ),
        'icon_rotate'      => array(
            'conditions' => 'icon_dot',
            'type'    => 'checkbox',
            'heading' => 'Icon Rotate',
        ),
        'icon_radius' => array(
          'type' => 'slider',
          'heading' => __('Icon Radius'),
          'unit' => 'px',
          'max' => 100,
          'min' => 0,
        ),
      
        'dashed' => array(
          'type'    => 'slider',
          'heading' => __( 'Dashed Width' ),
          'unit' => 'px',
          'max'        => 20,
          'min'        => 0,
          'step'       => 1,
        ),
        'dashed_spacing' => array(
          'conditions' => 'dashed',
          'type'    => 'slider',
          'heading' => __( 'Dashed Spacing' ),
          'default'    => '2',
          'unit' => '+',
          'max'        => 31,
          'min'        => 0,
          'step'       => 1,
        ),
        'dashed_radius' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type' => 'slider',
          'heading' => __('Dashed Radius'),
          'default' => 0,
          'unit' => 'px',
          'max' => 50,
          'min' => 0,
        ),
        'dashed_color' => array(
          'conditions' => 'dashed',
          'type' => 'colorpicker',
          'heading' => __('Dashed Color'),
          'default' => '',
          'format' => 'rgb',
          'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
        ),
        'dashed_gradient' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type' => 'colorpicker',
          'heading' => __('Dashed Color Gradient'),
          'default' => '',
          'format' => 'rgb',
          'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
        ),
        'dashed_length' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Dash Length' ),
          'default'    => '1',
          'unit' => '+',
          'max'        => 30,
          'min'        => 1,
          'step'       => 1,
        ),
        'dashed_slanting' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Slanting Angle' ),
          'default'    => '-60',
          'unit' => '+',
          'max'        => 60,
          'min'        => -60,
          'step'       => 5,
        ),
        'dashed_fade' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Fade' ),
          'unit' => '+',
          'default'    => '1',
          'max'        => 1,
          'min'        => 0,
          'step'       => 0.01,
        ),
        'dashed_diraction'      => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'checkbox',
          'heading' => 'Flip diraction',
        ),
        'dashed_animation' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Animation' ),
          'unit' => 's',
          'max'        => 1,
          'min'        => 0,
          'step'       => 0.1,
        ),
        'dashed_visibility' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
             'type' => 'select',
             'heading' => __('Visibility'),
             'default'    => '',
             'config'  => array(
               'placeholder' => __( 'Select...', 'ux-builder' ),
               'multiple'    => true,
               'options' => array(
                   'top'  => 'Top',
                   'left'  => 'Left',
                   'right'  => 'Right',
                   'bottom'  => 'Bottom',
               ),
             ),
         ),
),
);